deploy:
  provider: s3
  access_key_id: AKIA2AC63A4OIWJZJEOJ
  secret_access_key:
    secure: TvyOtCiiWsJ2MnsbRElDweGhnKkJrW3W4gkpvNobbaem5QtS9zEPBVdB7zTSoWgoZmL+BTGP/PQGygRotdwetKh9asr/4GRxYe6uio2DwxF7n/jCRGPSGtJUB7VVMzkMoysUWW8gCCt8nSpYgALJ+TcRzof6Y8UeX/GdNeReiN96DIcgqId2y2kHf3dQBHTCnEjKLbRvSVSm/vmvmko453h1/uWtRFVF5psEozltQjJLPH6CvFDnqNkLJsfoGR1ZM6HV9Y8iZHGvrQepU8x0Br4Q+uCl6jIWYhGT4m+uRLEwFLOma/RExgo1PDbxfH5sxXWMatac/ybO1M3+VssAwO1n8OgODbVIoH00CRoI46K5Fk7oci6SZiY5wmSo3zzLHujEVVvT8JbsjngqYKO3Pu2u/hBMaNSE4B5zjytTTEWuULQ1GnmUu/QBEkC5/fgqJYQQhJyT1Jz3Ep98obVgJawr0A0SKnyvy1Ov4wlcF9MlIOf8iQgM9U8VcmNB/iD17Jvw0Lwz4WLKmoBZYtyMnprVNbSariyV7NePgdytLLzT2C0zf8w973aVD7cV0hr63mnoSDvQMLykkIwCLbXOsYSuviQqHaXduYWKmjI0GP3M2B0lXJIPTm1y0t6GyQn6KnaHbCdd3KLAYiA5IeGA7wZvb/nrlKZBSARIYnYiI54=
  bucket: krissdotcc
