dist: bionic
before_install:
  - sudo apt-get update
language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: krissdotcc
  acl: public_read
  on:
    repo: kstrikis/krissdotcc
    branch: main
  skip_cleanup: 'true'
