language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIA2AC63A4OIWJZJEOJ
  secret_access_key:
    secure: FVeCpXj3lR0sFSlDl3C2uqfr7F42uloPpV4zl4a8tMkwn+ymT+94pN0FeyZIaAZIEqN8d/lbrbU5TNRjYUF70OckK8Hi/AuzerZI2q3TszpTN2fyvKCrKzUh3rpJoHViEaVSJoloIe3CAI/yoIwGTMvXNsy5cBjMunFJ7wtSj/D3fh9E74XejG//reHu0/oscZhpNIxwKZnjQ7iyRK5MtgAr0LtkTyXvzd169D08wfIyM1/Q1Zk6g6kX77sxllbp0zbSO6Ezjd/NdhLGAtcFyohUicWOquGnraaMvnQ0w9FvQ6FhytCuPoe9DFn4HjD+alMzw/r9LdV5tbGs179eZd2bFEfxLyO3YVcORr9CNYlDXwOJBMhGK7JgmauqLU9sup7zAxcmJbyUPTS6OrNb+KFHOP0MSkU8Idqi0URmveggzKPL2j1qtQtHxe0dmtZ6eNmeEy+Qoz3zCOMrHQuTQQVPKwZF38rfyjaA+/MPRBSrKKmiKp5xBWMxISBBUEIV3aX+9fZjNZflBt6hfW8EyH/gR7PVD4SFGkPpYz91p669+nx3NlbV3srYKuY/O6HqUeDC+Z7KK0QM8h2hen5DotQNwNFQMWh5Bq9OTrdMj0ZG/2YocMIrkofq5HQHuhdaf/MBKYq8WYZ1271PL93OMU27Qc6W8KFZngwkemu8N08=
  bucket: krissdotcc
  acl: public_read
  on:
    repo: kstrikis/krissdotcc
    branch: main
  skip_cleanup: 'true'
