language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIA2AC63A4OIWJZJEOJ
  secret_access_key:
    secure: FtoqEv8D5jzm8bAW//7UeVMoexttj9X9ZxkIISBn5F+DyTLwMj+vrJBasjdKWO3ppoEG07rogleF3qY+NqbYE/TtkHwP3qISgC2WXXi/+8F6lXT6AMIccMHOqjNT30Ggm7CLdFEY+yZ5CMzADJuxk11S2AkqUrWiCc0viVBYg31j5fmtcKLsXxaexhFfiRm9CCsoWLuUcbxldrzQSDJP3lSoke1CinrypXOwOVVdwr6nxXmZOnFLqP4s9ZyK8yHpl2E9i2EulBnDf4ETXK3w3q693WK955PZo2lJmAJehXmKVcMjHloHpRtUqaKHL0fgbLCACeCugmI40sfrIPiv5GSkuL8OB/yq1UcGuDAh+8OQfL+dlnME1T0/JHA3DwTJt64Ohm/19Z0cl6dYmVe4gUTT/eiAB/hm38NgMKOXJgpjkcD8KbTJa5R0zhtESyst71U04GsUKpXrrUpNysOBS+XAMhjSVAx1/LHIh9hLJl/bcYd7MwvndtVLLXTlGyQkFt6ZpBqNYvh2gbuTR+uPYQyS0hhe+puJ/szMq/0R5v/qPrLyQIEtExphVIwbyZMaifyLcMKM/0+LJ59DfLRDDbIRcCITIlo0/MxpBAKG/6PfOvtxfUCdRnH2JEYwX4Y/SEG6y6t7ZcYepn5RFxzrBwsz/JjbSqIgh/F9QR3X69w=
  bucket: krissdotcc
  acl: public_read
  on:
    repo: kstrikis/krissdotcc
    branch: main
  skip_cleanup: 'true'
